# Generated by Django 3.2.9 on 2021-11-16 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('url', models.CharField(max_length=128, verbose_name='地址')),
                ('type', models.CharField(choices=[('交易', '交易'), ('行情', '行情')], max_length=16, verbose_name='类型')),
                ('operator', models.CharField(choices=[('电信', '电信'), ('联通', '联通')], max_length=16, verbose_name='运营商')),
            ],
            options={
                'verbose_name': '前置地址',
                'verbose_name_plural': '前置地址列表',
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('contract_type', models.CharField(choices=[('股票', '股票'), ('期货', '期货'), ('期权', '期权')], max_length=32, verbose_name='市场')),
                ('identify', models.CharField(max_length=32, verbose_name='唯一标志')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('fake', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='虚拟资金')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='可用资金')),
                ('current', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='动态权益')),
                ('pre_balance', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='静态权益')),
                ('market_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_address', to='panel.address', verbose_name='行情前置')),
                ('trade_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_address', to='panel.address', verbose_name='交易前置')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户列表',
            },
        ),
        migrations.CreateModel(
            name='DailyBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('SHFE', '上期所'), ('DCE', '大商所'), ('CZCE', '郑商所'), ('CFFEX', '中金所')], max_length=8, verbose_name='交易所')),
                ('code', models.CharField(db_index=True, max_length=8, null=True, verbose_name='品种代码')),
                ('expire_date', models.IntegerField(null=True, verbose_name='交割时间')),
                ('time', models.DateField(db_index=True, verbose_name='时间')),
                ('open', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='开盘价')),
                ('high', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='最低价')),
                ('close', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='收盘价')),
                ('settlement', models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='结算价')),
                ('volume', models.IntegerField(verbose_name='成交量')),
                ('open_interest', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='持仓量')),
            ],
            options={
                'verbose_name': '日K线',
                'verbose_name_plural': '日K线列表',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('SHFE', '上期所'), ('DCE', '大商所'), ('CZCE', '郑商所'), ('CFFEX', '中金所')], max_length=8, verbose_name='交易所')),
                ('section', models.CharField(blank=True, choices=[('1AgriculturalCommodities', '农产品'), ('2NonAgriculturalCommodities', '工业品'), ('3Equities', '股指'), ('4Rates', '利率'), ('5Currencies', '货币')], max_length=48, null=True, verbose_name='分类')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='名称')),
                ('product_code', models.CharField(max_length=16, unique=True, verbose_name='代码')),
                ('sina_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='新浪代码')),
                ('all_inst', models.CharField(blank=True, max_length=128, null=True, verbose_name='品种列表')),
                ('main_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='主力合约')),
                ('last_main', models.CharField(blank=True, max_length=16, null=True, verbose_name='上个主力')),
                ('change_time', models.DateTimeField(blank=True, null=True, verbose_name='切换时间')),
                ('night_trade', models.BooleanField(default=False, verbose_name='夜盘')),
                ('volume_multiple', models.IntegerField(blank=True, null=True, verbose_name='合约乘数')),
                ('price_tick', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='最小变动')),
                ('margin_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='保证金率')),
                ('fee_money', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='金额手续费')),
                ('fee_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='手数手续费')),
                ('up_limit_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='涨停幅度')),
                ('down_limit_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='跌停幅度')),
            ],
            options={
                'verbose_name': '合约',
                'verbose_name_plural': '合约列表',
            },
        ),
        migrations.CreateModel(
            name='MainBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('SHFE', '上期所'), ('DCE', '大商所'), ('CZCE', '郑商所'), ('CFFEX', '中金所')], max_length=8, verbose_name='交易所')),
                ('product_code', models.CharField(db_index=True, max_length=8, null=True, verbose_name='品种代码')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='合约代码')),
                ('time', models.DateField(db_index=True, verbose_name='时间')),
                ('open', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='开盘价')),
                ('high', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='最低价')),
                ('close', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='收盘价')),
                ('settlement', models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='结算价')),
                ('volume', models.IntegerField(verbose_name='成交量')),
                ('open_interest', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='持仓量')),
                ('basis', models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='基差')),
            ],
            options={
                'verbose_name': '主力连续日K线',
                'verbose_name_plural': '主力连续日K线列表',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(max_length=13, verbose_name='报单号')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='合约代码')),
                ('front', models.IntegerField(verbose_name='前置编号')),
                ('session', models.IntegerField(verbose_name='会话编号')),
                ('price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='报单价格')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='手数')),
                ('direction', models.CharField(choices=[('多', '多'), ('空', '空')], max_length=8, verbose_name='方向')),
                ('offset_flag', models.CharField(choices=[('开', '开'), ('平', '平'), ('平今', '平今')], max_length=8, verbose_name='开平')),
                ('status', models.CharField(choices=[('0', '全部成交'), ('1', '部分成交还在队列中'), ('2', '部分成交不在队列中'), ('3', '未成交还在队列中'), ('4', '未成交不在队列中'), ('5', '撤单'), ('a', '未知'), ('b', '尚未触发'), ('c', '已触发')], max_length=16, verbose_name='状态')),
                ('send_time', models.DateTimeField(verbose_name='发送时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.broker', verbose_name='账户')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.instrument', verbose_name='品种')),
            ],
            options={
                'verbose_name': '报单',
                'verbose_name_plural': '报单列表',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.broker', verbose_name='账户')),
                ('force_opens', models.ManyToManyField(blank=True, related_name='force_opens', to='panel.Instrument', verbose_name='手动开仓')),
                ('instruments', models.ManyToManyField(to='panel.Instrument', verbose_name='交易品种')),
            ],
            options={
                'verbose_name': '策略',
                'verbose_name_plural': '策略列表',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='合约代码')),
                ('direction', models.CharField(choices=[('多', '多'), ('空', '空')], max_length=8, verbose_name='方向')),
                ('open_time', models.DateTimeField(verbose_name='开仓日期')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='平仓日期')),
                ('shares', models.IntegerField(blank=True, null=True, verbose_name='手数')),
                ('filled_shares', models.IntegerField(blank=True, null=True, verbose_name='已成交手数')),
                ('closed_shares', models.IntegerField(blank=True, null=True, verbose_name='已平仓手数')),
                ('avg_entry_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='持仓均价')),
                ('avg_exit_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='平仓均价')),
                ('profit', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='持仓盈亏')),
                ('frozen_margin', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='冻结保证金')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='手续费')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.broker', verbose_name='账户')),
                ('close_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_order', to='panel.order', verbose_name='平仓报单')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.instrument', verbose_name='品种')),
                ('open_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_order', to='panel.order', verbose_name='开仓报单')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.strategy', verbose_name='策略')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录列表',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, null=True, verbose_name='当前合约')),
                ('type', models.CharField(choices=[('换月平旧', '换月平旧'), ('换月开新', '换月开新'), ('买开', '买开'), ('卖开', '卖开'), ('卖平', '卖平'), ('买平', '买平')], max_length=16, verbose_name='信号类型')),
                ('trigger_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='触发值')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='价格')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('trigger_time', models.DateTimeField(verbose_name='发生时间')),
                ('priority', models.IntegerField(choices=[(0, '低'), (1, '普通'), (2, '高')], default=1, verbose_name='优先级')),
                ('processed', models.BooleanField(blank=True, default=False, verbose_name='已处理')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.instrument', verbose_name='品种')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.strategy', verbose_name='策略')),
            ],
            options={
                'verbose_name': '信号',
                'verbose_name_plural': '信号列表',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='日期')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='资金')),
                ('unit_count', models.IntegerField(null=True, verbose_name='单位乘数')),
                ('NAV', models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='单位净值')),
                ('accumulated', models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='累计净值')),
                ('dividend', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='分红')),
                ('used_margin', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='占用保证金')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.broker', verbose_name='账户')),
            ],
            options={
                'verbose_name': '绩效',
                'verbose_name_plural': '绩效列表',
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='参数名')),
                ('str_value', models.CharField(blank=True, max_length=128, null=True, verbose_name='字符串值')),
                ('int_value', models.IntegerField(blank=True, null=True, verbose_name='整数值')),
                ('float_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='浮点值')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.strategy', verbose_name='策略')),
            ],
            options={
                'verbose_name': '策略参数',
                'verbose_name_plural': '策略参数列表',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.strategy', verbose_name='策略'),
        ),
    ]
