# Generated by Django 3.2.9 on 2021-11-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='broker',
            table='broker',
        ),
        migrations.AlterModelTable(
            name='dailybar',
            table='dailybar',
        ),
        migrations.AlterModelTable(
            name='instrument',
            table='instrument',
        ),
        migrations.AlterModelTable(
            name='mainbar',
            table='mainbar',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='param',
            table='param',
        ),
        migrations.AlterModelTable(
            name='performance',
            table='performance',
        ),
        migrations.AlterModelTable(
            name='signal',
            table='signal',
        ),
        migrations.AlterModelTable(
            name='strategy',
            table='strategy',
        ),
        migrations.AlterModelTable(
            name='trade',
            table='trade',
        ),
    ]
