# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='market_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_address', to='panel.Address', verbose_name='行情前置'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='trade_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_address', to='panel.Address', verbose_name='交易前置'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='all_inst',
            field=models.CharField(max_length=128, verbose_name='合约月份汇总'),
        ),
        migrations.AlterField(
            model_name='order',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Broker', verbose_name='券商'),
        ),
        migrations.AlterField(
            model_name='order',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.Strategy', verbose_name='策略'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Broker', verbose_name='券商'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Broker', verbose_name='券商'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='close_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_order', to='panel.Order', verbose_name='平仓报单'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='open_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_order', to='panel.Order', verbose_name='开仓报单'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.Strategy', verbose_name='策略'),
        ),
    ]
