# Generated by Django 3.2.9 on 2021-11-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20211122_1042'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table=None,
        ),
        migrations.AlterModelTable(
            name='broker',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dailybar',
            table=None,
        ),
        migrations.AlterModelTable(
            name='instrument',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mainbar',
            table=None,
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='param',
            table=None,
        ),
        migrations.AlterModelTable(
            name='performance',
            table=None,
        ),
        migrations.AlterModelTable(
            name='signal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='strategy',
            table=None,
        ),
        migrations.AlterModelTable(
            name='trade',
            table=None,
        ),
    ]
