# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20160812_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='all_inst',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='合约月份汇总'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='change_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='切换时间'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='last_main',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='上个主力合约'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='main_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='主力合约'),
        ),
    ]
