# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20160812_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='dailybar',
            name='exchange',
            field=models.CharField(choices=[('SHFE', '上期所'), ('DCE', '大商所'), ('CZCE', '郑商所'), ('CFFEX', '中金所')], max_length=8, verbose_name='交易所'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='exchange',
            field=models.CharField(choices=[('SHFE', '上期所'), ('DCE', '大商所'), ('CZCE', '郑商所'), ('CFFEX', '中金所')], max_length=8, verbose_name='交易所'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exchange',
            field=models.CharField(choices=[('SHFE', '上期所'), ('DCE', '大商所'), ('CZCE', '郑商所'), ('CFFEX', '中金所')], max_length=8, verbose_name='交易所'),
        ),
    ]
