# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20160812_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailybar',
            name='code',
        ),
        migrations.AddField(
            model_name='dailybar',
            name='basis',
            field=models.FloatField(null=True, verbose_name='基差'),
        ),
        migrations.AddField(
            model_name='dailybar',
            name='cur_code',
            field=models.CharField(max_length=8, null=True, verbose_name='当前合约'),
        ),
        migrations.AddField(
            model_name='dailybar',
            name='product_code',
            field=models.CharField(max_length=8, null=True, verbose_name='品种代码'),
        ),
    ]
