# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20160816_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('SHFE', '上期所'), ('DCE', '大商所'), ('CZCE', '郑商所'), ('CFFEX', '中金所')], max_length=8, verbose_name='交易所')),
                ('product_code', models.CharField(max_length=8, null=True, verbose_name='品种代码')),
                ('cur_code', models.CharField(max_length=8, null=True, verbose_name='当前合约')),
                ('time', models.DateField(verbose_name='时间')),
                ('open', models.FloatField(verbose_name='开盘价')),
                ('high', models.FloatField(verbose_name='最高价')),
                ('low', models.FloatField(verbose_name='最低价')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('volume', models.IntegerField(verbose_name='成交量')),
                ('open_interest', models.IntegerField(verbose_name='持仓量')),
                ('basis', models.FloatField(null=True, verbose_name='基差')),
            ],
            options={
                'verbose_name': '主力连续日K线',
                'verbose_name_plural': '主力连续日K线集合',
            },
        ),
        migrations.RenameField(
            model_name='dailybar',
            old_name='product_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='dailybar',
            name='basis',
        ),
        migrations.RemoveField(
            model_name='dailybar',
            name='cur_code',
        ),
    ]
