# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20160824_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybar',
            name='open_interest',
            field=models.FloatField(verbose_name='持仓量'),
        ),
        migrations.AlterField(
            model_name='mainbar',
            name='open_interest',
            field=models.FloatField(verbose_name='持仓量'),
        ),
    ]
