# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20160825_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybar',
            name='expire_date',
            field=models.IntegerField(null=True, verbose_name='交割时间'),
        ),
    ]
