# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_dailybar_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='参数名')),
                ('str_value', models.CharField(max_length=128, null=True, verbose_name='字符串值')),
                ('int_value', models.IntegerField(null=True, verbose_name='整数值')),
                ('float_value', models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='浮点值')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Strategy', verbose_name='策略')),
            ],
            options={
                'verbose_name': '策略参数',
                'verbose_name_plural': '策略参数集合',
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16, verbose_name='信号类型')),
                ('trigger_time', models.DateTimeField(verbose_name='发生时间')),
                ('priority', models.IntegerField(verbose_name='优先级')),
                ('processed', models.BooleanField(default=False, verbose_name='已处理')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Instrument', verbose_name='品种')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Strategy', verbose_name='策略')),
            ],
        ),
        migrations.AlterField(
            model_name='dailybar',
            name='close',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='收盘价'),
        ),
        migrations.AlterField(
            model_name='dailybar',
            name='high',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='dailybar',
            name='low',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='dailybar',
            name='open',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='开盘价'),
        ),
        migrations.AlterField(
            model_name='dailybar',
            name='open_interest',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='持仓量'),
        ),
        migrations.AlterField(
            model_name='mainbar',
            name='basis',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='基差'),
        ),
        migrations.AlterField(
            model_name='mainbar',
            name='close',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='收盘价'),
        ),
        migrations.AlterField(
            model_name='mainbar',
            name='high',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='mainbar',
            name='low',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='mainbar',
            name='open',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='开盘价'),
        ),
        migrations.AlterField(
            model_name='mainbar',
            name='open_interest',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='持仓量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='报单价格'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='avg_entry_price',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='持仓均价'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='avg_exit_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='平仓均价'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='手续费'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='frozen_margin',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='冻结保证金'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='持仓盈亏'),
        ),
    ]
