# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_auto_20160829_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='instruments',
            field=models.ManyToManyField(to='panel.Instrument', verbose_name='交易品种'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='open_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_order', to='panel.Order', verbose_name='开仓报单'),
        ),
    ]
