# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_auto_20160830_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='手续费'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='frozen_margin',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='冻结保证金'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='持仓盈亏'),
        ),
    ]
