# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20160830_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='日期')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='资金')),
                ('unit_count', models.IntegerField(null=True, verbose_name='单位乘数')),
                ('NAV', models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='单位净值')),
                ('accumulated', models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='累计净值')),
                ('dividend', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='分红')),
            ],
        ),
        migrations.AddField(
            model_name='broker',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='可用资金'),
        ),
        migrations.AddField(
            model_name='broker',
            name='current',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='动态权益'),
        ),
        migrations.AddField(
            model_name='broker',
            name='pre_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='静态权益'),
        ),
        migrations.AddField(
            model_name='performance',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Broker', verbose_name='券商'),
        ),
    ]
