# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_auto_20160830_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '前置地址', 'verbose_name_plural': '前置地址列表'},
        ),
        migrations.AlterModelOptions(
            name='broker',
            options={'verbose_name': '账户', 'verbose_name_plural': '账户列表'},
        ),
        migrations.AlterModelOptions(
            name='dailybar',
            options={'verbose_name': '日K线', 'verbose_name_plural': '日K线列表'},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': '合约', 'verbose_name_plural': '合约列表'},
        ),
        migrations.AlterModelOptions(
            name='mainbar',
            options={'verbose_name': '主力连续日K线', 'verbose_name_plural': '主力连续日K线列表'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '报单', 'verbose_name_plural': '报单列表'},
        ),
        migrations.AlterModelOptions(
            name='param',
            options={'verbose_name': '策略参数', 'verbose_name_plural': '策略参数列表'},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'verbose_name': '绩效', 'verbose_name_plural': '绩效列表'},
        ),
        migrations.AlterModelOptions(
            name='signal',
            options={'verbose_name': '信号', 'verbose_name_plural': '信号列表'},
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': '策略', 'verbose_name_plural': '策略列表'},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'verbose_name': '交易记录', 'verbose_name_plural': '交易记录列表'},
        ),
        migrations.AddField(
            model_name='instrument',
            name='fee_money',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='金额手续费'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='fee_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='手数手续费'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='margin_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True, verbose_name='保证金率'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='volume_multiple',
            field=models.IntegerField(blank=True, null=True, verbose_name='合约乘数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Broker', verbose_name='账户'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Broker', verbose_name='账户'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Broker', verbose_name='账户'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Broker', verbose_name='账户'),
        ),
    ]
