# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_auto_20160831_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='down_limit_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='跌停幅度'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='night_trade',
            field=models.BooleanField(default=False, verbose_name='夜盘交易'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='up_limit_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='涨停幅度'),
        ),
    ]
