# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_auto_20160901_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='signal',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='trigger_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='触发值'),
        ),
    ]
