# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_auto_20160902_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybar',
            name='settlement',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='结算价'),
        ),
        migrations.AddField(
            model_name='mainbar',
            name='settlement',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True, verbose_name='结算价'),
        ),
    ]
