# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_auto_20160902_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='price_tick',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='最小变动价位'),
        ),
    ]
