# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_instrument_price_tick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='all_inst',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='品种列表'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='last_main',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='上个主力'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='night_trade',
            field=models.BooleanField(default=False, verbose_name='夜盘'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='price_tick',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='最小变动'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='product_code',
            field=models.CharField(max_length=16, unique=True, verbose_name='代码'),
        ),
    ]
