# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_auto_20160902_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='fee_money',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True, verbose_name='金额手续费'),
        ),
    ]
