# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_auto_20160903_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='手续费'),
        ),
    ]
