# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_auto_20160904_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='exchange',
        ),
        migrations.AddField(
            model_name='trade',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='合约代码'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Instrument', verbose_name='品种'),
        ),
    ]
