# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_auto_20160904_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='used_margin',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='占用保证金'),
        ),
    ]
