# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_performance_used_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='合约代码'),
        ),
        migrations.AddField(
            model_name='order',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='手数'),
        ),
        migrations.AddField(
            model_name='trade',
            name='closed_shares',
            field=models.IntegerField(blank=True, null=True, verbose_name='已平仓手数'),
        ),
        migrations.AlterField(
            model_name='order',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Instrument', verbose_name='品种'),
        ),
    ]
