# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0024_auto_20160905_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='avg_entry_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='持仓均价'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='手续费'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='frozen_margin',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='冻结保证金'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='持仓盈亏'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='shares',
            field=models.IntegerField(blank=True, null=True, verbose_name='手数'),
        ),
    ]
