# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0025_auto_20160906_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='force_opens',
            field=models.ManyToManyField(related_name='force_opens', to='panel.Instrument', verbose_name='手动开仓'),
        ),
    ]
