# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_strategy_force_opens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybar',
            name='code',
            field=models.CharField(db_index=True, max_length=8, null=True, verbose_name='品种代码'),
        ),
        migrations.AlterField(
            model_name='dailybar',
            name='time',
            field=models.DateField(db_index=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='mainbar',
            name='product_code',
            field=models.CharField(db_index=True, max_length=8, null=True, verbose_name='品种代码'),
        ),
        migrations.AlterField(
            model_name='mainbar',
            name='time',
            field=models.DateField(db_index=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offset_flag',
            field=models.CharField(choices=[('开', '开'), ('平', '平'), ('平今', '平今')], max_length=8, verbose_name='开平'),
        ),
    ]
