# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0027_auto_20160912_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainbar',
            name='cur_code',
        ),
        migrations.AddField(
            model_name='mainbar',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='合约代码'),
        ),
        migrations.AddField(
            model_name='signal',
            name='code',
            field=models.CharField(max_length=8, null=True, verbose_name='当前合约'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='type',
            field=models.CharField(choices=[('换月平旧', '换月平旧'), ('换月开新', '换月开新'), ('买开', '买开'), ('卖开', '卖开'), ('卖平', '卖平'), ('买平', '买平')], max_length=16, verbose_name='信号类型'),
        ),
    ]
