# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0028_auto_20160920_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='section',
            field=models.CharField(blank=True, choices=[('AgriculturalCommodities', '农产品'), ('NonAgriculturalCommodities', '工业品'), ('Equities', '股指'), ('Rates', '利率'), ('Currencies', '货币')], max_length=48, null=True, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='force_opens',
            field=models.ManyToManyField(blank=True, related_name='force_opens', to='panel.Instrument', verbose_name='手动开仓'),
        ),
    ]
