# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-03 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0030_auto_20161026_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='sina_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='新浪代码'),
        ),
    ]
